// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF5hHG3k9l1NTF6cC8jR6JIQSAm32GDbE',
    appId: '1:215693302575:web:73c718a866938dd3795fda',
    messagingSenderId: '215693302575',
    projectId: 'remindr-4e80c',
    authDomain: 'remindr-4e80c.firebaseapp.com',
    storageBucket: 'remindr-4e80c.firebasestorage.app',
    measurementId: 'G-YFQ3EEP47R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYIRt2X_Rr7OmIz0DKZm46vZzDs8hcr88',
    appId: '1:215693302575:android:983ea9e371e297f7795fda',
    messagingSenderId: '215693302575',
    projectId: 'remindr-4e80c',
    storageBucket: 'remindr-4e80c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhEllRCOnUs5ysET6NmqOiJTrLqgiEZrA',
    appId: '1:215693302575:ios:c33b98315b5b8ad4795fda',
    messagingSenderId: '215693302575',
    projectId: 'remindr-4e80c',
    storageBucket: 'remindr-4e80c.firebasestorage.app',
    iosBundleId: 'com.example.smartProcure',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhEllRCOnUs5ysET6NmqOiJTrLqgiEZrA',
    appId: '1:215693302575:ios:c33b98315b5b8ad4795fda',
    messagingSenderId: '215693302575',
    projectId: 'remindr-4e80c',
    storageBucket: 'remindr-4e80c.firebasestorage.app',
    iosBundleId: 'com.example.smartProcure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF5hHG3k9l1NTF6cC8jR6JIQSAm32GDbE',
    appId: '1:215693302575:web:163b460194d40630795fda',
    messagingSenderId: '215693302575',
    projectId: 'remindr-4e80c',
    authDomain: 'remindr-4e80c.firebaseapp.com',
    storageBucket: 'remindr-4e80c.firebasestorage.app',
    measurementId: 'G-VX65M1XWS6',
  );
}
